import type { PricingContent, PricingTier } from '@/types/database';

export const DEFAULT_PRICING_TIERS: PricingTier[] = [
  {
    id: 'trial-pack',
    title_en: 'No-Risk Test Drive Sprint',
    title_bn: 'নো-রিস্ক টেস্ট ড্রাইভ স্প্রিন্ট',
    target_en: 'First-Time Brand Partners (Zero Contract)',
    target_bn: 'নতুন ক্লায়েন্টদের জন্য (কোনো চুক্তি নেই)',
    price_en: '৳3,999',
    price_bn: '৳৩,৯৯৯',
    desc_en: 'Test our data-driven creative process with zero long-term commitment. 5 high-converting Meta Ads in 48 hours to validate quality before any retainer.',
    desc_bn: 'কোনো দীর্ঘমেয়াদী চুক্তি বা সাবস্ক্রিপশন ছাড়া আমাদের কাজের কোয়ালিটি যাচাই করুন। মাত্র ৪৮ ঘণ্টায় ৫টি মেটা অ্যাড—বিকাশ ও নগদে পেমেন্ট সুবিধা।',
    outcome_tag_en: 'Zero Risk • 48h Turnaround',
    outcome_tag_bn: 'কোনো ঝুঁকি নেই • ৪৮ ঘণ্টায় রেডি',
    deliverables_en: [
      '5 High-Converting Meta Ad Creatives (Feed + Story)',
      'Persuasive Bengali & English Sales Copywriting',
      '48-Hour Rapid Delivery Guarantee',
      'bKash, Nagad & Local Bank Payment Support',
      '100% Satisfaction & Unlimited Free Revisions',
    ],
    deliverables_bn: [
      '৫টি হাই-কনভার্টিং মেটা অ্যাড (ফিড + স্টোরি সাইজ)',
      'অর্ডার বৃদ্ধিকারী বাংলা ও ইংরেজি সেলস কপিরাইটিং',
      '৪৮ ঘণ্টার নিশ্চিত দ্রুত ডেলিভারি',
      'বিকাশ, নগদ ও যেকোনো দেশি ব্যাংক পেমেন্ট সাপোর্ট',
      '১০০% ফ্রি রিভিশন নিশ্চয়তা (সন্তুষ্ট না হওয়া পর্যন্ত)',
    ],
    cta_en: 'Book ৳3,999 Test Drive on WhatsApp',
    cta_bn: 'হোয়াটসঅ্যাপে ৳৩,৯৯৯ টেস্ট ড্রাইভ শুরু করুন',
    whatsapp_url: "https://wa.me/8801346288210?text=Hi%20POLISHED%2C%20I%20want%20to%20start%20the%20%E0%A7%B33999%20No-Risk%20Test%20Drive%20Sprint.",
    featured: false,
  },
  {
    id: 'growth-pack',
    title_en: 'D2C Brand Growth Engine',
    title_bn: 'D2C ব্র্যান্ড গ্রোথ ইঞ্জিন',
    target_en: 'Scaling Skincare & D2C Brands',
    target_bn: 'স্কেলিং স্কিনকেয়ার ও D2C ব্র্যান্ড',
    price_en: '৳32,299 / month',
    price_bn: '৳৩২,২৯৯ / মাস',
    desc_en: 'Complete visual performance engine to automate your sales funnel, slash CAC, and maintain luxury market dominance across channels.',
    desc_bn: 'আপনার সেলস ফানেল অটোমেট করা, CAC হ্রাস করা এবং প্রিমিয়াম ব্র্যান্ড ভ্যালু ধরে রেখে সেলস স্কেল করার জন্য পূর্ণাঙ্গ কন্টেন্ট ইঞ্জিন।',
    outcome_tag_en: 'Most Popular for D2C Brands',
    outcome_tag_bn: 'D2C ব্র্যান্ডদের সর্বাধিক পছন্দের',
    deliverables_en: [
      '15 High-Converting Feed & Ad Creatives / mo',
      'High-Trust Storefront / PDP Conversion Graphics',
      'Persuasive Bengali Sales Copy for Every Creative',
      'AOV-Maximizing Combo & Bundle Offer Visuals',
      'Unlimited Minor Revisions & Priority WhatsApp Support',
    ],
    deliverables_bn: [
      '১৫টি হাই-কনভার্টিং ফিড ও অ্যাড ক্রিয়েটিভ / মাস',
      'হাই-ট্রাস্ট স্টোরফ্রন্ট / PDP কনভার্শন গ্রাফিক্স',
      'প্রতিটি অ্যাডের জন্য মনস্তাত্ত্বিক বাংলা সেলস কপি',
      'গড় অর্ডার ভ্যালু (AOV) বৃদ্ধিকারী কম্বো অফার ভিজ্যুয়াল',
      'আনলিমিটেড মাইনর রিভিশন ও প্রায়োরিটি সাপোর্ট',
    ],
    cta_en: 'Start Growth Engine',
    cta_bn: 'গ্রোথ ইঞ্জিন শুরু করুন',
    whatsapp_url: "https://wa.me/8801346288210?text=Hi%20POLISHED%2C%20I%20am%20interested%20in%20the%20D2C%20Brand%20Growth%20Engine%20(%E0%A7%B332299/mo).",
    featured: true,
  },
  {
    id: 'agency-pack',
    title_en: 'White-Label Agency Partner',
    title_bn: 'হোয়াইট-লেবেল এজেন্সি পার্টনার',
    target_en: 'Performance Marketing Agencies',
    target_bn: 'মার্কেটিং ও মিডিয়া বায়িং এজেন্সি',
    price_en: '৳48,500 / month',
    price_bn: '৳৪৮,৫০০ / মাস',
    desc_en: 'The invisible creative powerhouse for marketing agencies. Scale your clients’ ad campaigns without hiring expensive in-house designers.',
    desc_bn: 'মার্কেটিং এজেন্সির ইনভিজিবল ব্যাকএন্ড ক্রিয়েটিভ পাওয়ারহাউস। ইন-হাউস ডিজাইনারের বেতন ও খরচের ঝামেলা ছাড়াই ক্লায়েন্টের ফলাফল বহুগুণ স্কেল করুন।',
    outcome_tag_en: 'Scale Without Team Bottlenecks',
    outcome_tag_bn: 'টিম হ্যাসেল ছাড়াই ক্লায়েন্ট স্কেলিং',
    deliverables_en: [
      'Up to 30 White-Label Client Creatives / mo',
      'Strict 48-Hour Rapid Sprint Delivery SLA',
      'White-Label Figma / Drive (Zero POLISHED Branding)',
      'High ROAS Angles Designed to Maximize Client Retention',
      'Direct WhatsApp / Slack Access with Creative Lead',
    ],
    deliverables_bn: [
      'মাসে সর্বোচ্চ ৩০টি হোয়াইট-লেবেল ক্লায়েন্ট ক্রিয়েটিভ',
      'কঠোর ৪৮ ঘণ্টার র্যাপিড ডেলিভারি SLA',
      'হোয়াইট-লেবেল ফিগমা/ড্রাইভ (আমাদের কোনো ব্র্যান্ডিং থাকবে না)',
      'ক্লায়েন্ট রিটেনশন ও আরওএএস সর্বোচ্চ করার আর্কিটেকচার',
      'ক্রিয়েটিভ লিডের সাথে ডিরেক্ট স্ল্যাক/হোয়াটসঅ্যাপ চ্যানেল',
    ],
    cta_en: 'Join Agency Partner Program',
    cta_bn: 'এজেন্সি পার্টনারশিপ শুরু করুন',
    whatsapp_url: "https://wa.me/8801346288210?text=Hi%20POLISHED%2C%20I%20am%20interested%20in%20the%20White-Label%20Agency%20Partner%20Plan%20(%E0%A7%B348500/mo).",
    featured: false,
  },
];

export const DEFAULT_PRICING: PricingContent = {
  labelEn: 'Investment & ROI',
  labelBn: 'ইনভেস্টমেন্ট ও ROI',
  titleEn: 'Performance Creative Sprints.',
  titleEmEn: 'Transparent, ROI-focused pricing.',
  titleBn: 'পারফরম্যান্স ক্রিয়েটিভ স্প্রিন্ট।',
  titleEmBn: 'স্বচ্ছ বিনিয়োগ, পরিমাপযোগ্য ফলাফল।',
  customHeadingEn: 'Need a Custom Scale Solution?',
  customHeadingBn: 'কাস্টম স্কেলিং সলিউশন প্রয়োজন?',
  customDescEn: "Let's craft a bespoke visual performance strategy tailored exactly to your brand's unique revenue targets and P&L.",
  customDescBn: 'আপনার ব্র্যান্ডের নির্দিষ্ট রেভিনিউ টার্গেট এবং P&L অনুযায়ী একটি কাস্টম ভিজ্যুয়াল স্ট্র্যাটেজি তৈরি করতে আমাদের সাথে কথা বলুন।',
  customCtaEn: 'Request Custom Growth Quote',
  customCtaBn: 'কাস্টম কোটেশন রিকোয়েস্ট করুন',
  tiers: DEFAULT_PRICING_TIERS,
};

export function makePricingTierId() {
  return `tier-${Math.random().toString(36).slice(2, 9)}`;
}
