import type { PricingContent, PricingTier } from '@/types/database';

export const DEFAULT_PRICING_TIERS: PricingTier[] = [
  {
    id: 'trial-pack',
    title_en: 'No-Risk Test Drive Sprint',
    title_bn: 'বিজ্ঞাপন টেস্ট ড্রাইভ স্প্রিন্ট',
    target_en: 'Stop Burning Ad Money (Zero Risk)',
    target_bn: 'বিজ্ঞাপনের টাকা অপচয় বন্ধের ট্রায়াল',
    price_en: '৳3,999',
    price_bn: '৳৩,৯৯৯',
    desc_en: 'Stop burning cash on generic Canva ads. Get 5 high-converting Meta ad creatives in 48 hours to test our work before any big commitment.',
    desc_bn: 'ক্যানভা টেমপ্লেটের পেছনে টাকা নষ্ট বন্ধ করুন। কোনো দীর্ঘমেয়াদী চুক্তি ছাড়াই মাত্র ৪৮ ঘণ্টায় ৫টি হাই-কনভার্টিং ক্রিয়েটিভ দিয়ে নিজে পরীক্ষা করে দেখুন।',
    outcome_tag_en: 'Zero Lock-in • 48h Delivery',
    outcome_tag_bn: 'কোনো চুক্তি নেই • ৪৮ ঘণ্টায় রেডি',
    deliverables_en: [
      '5 High-Converting Meta Ad Creatives (Feed + Story)',
      'Persuasive Bengali & English Sales Copy',
      'Strict 48-Hour Rapid Delivery Guarantee',
      'bKash, Nagad & Local Bank Payment Support',
      '100% Free Revisions until you are satisfied',
    ],
    deliverables_bn: [
      '৫টি হাই-কনভার্টিং মেটা ক্রিয়েটিভ (ফিড ও স্টোরি সাইজ)',
      'অর্ডার বাড়ানোর জন্য খাঁটি বাংলা সেলস কপি',
      '৪৮ ঘণ্টার নিশ্চিত দ্রুত ডেলিভারি',
      'বিকাশ, নগদ ও দেশি ব্যাংক পেমেন্ট সাপোর্ট',
      'মনমতো না হওয়া পর্যন্ত ১০০% ফ্রি রিভিশন',
    ],
    cta_en: 'Start ৳3,999 Test Drive',
    cta_bn: '৳৩,৯৯৯ টেস্ট ড্রাইভ শুরু করুন',
    whatsapp_url: "https://wa.me/8801346288210?text=Hi%20POLISHED%2C%20I%20want%20to%20start%20the%20%E0%A7%B33999%20No-Risk%20Test%20Drive%20Sprint.",
    featured: false,
  },
  {
    id: 'growth-pack',
    title_en: 'D2C Brand Growth Partner',
    title_bn: 'D2C ব্র্যান্ড গ্রোথ পার্টনার',
    target_en: 'Scaling Skincare & D2C Brands',
    target_bn: 'সেলস ও AOV বাড়ানোর ফুল গ্রোথ পার্টনার',
    price_en: '৳32,299 / month',
    price_bn: '৳৩২,২৯৯ / মাস',
    desc_en: 'Complete visual performance partner to slash your CPR, stop discount dependency, and scale monthly sales with authority visuals.',
    desc_bn: 'ডিসকাউন্ট দেওয়ার বাধ্যবাধকতা বন্ধ করে পুরো দামে বেশি সেলস আনতে এবং কাস্টমার একুইজিশন খরচ (CPR) কমাতে পূর্ণাঙ্গ মাসিক ক্রিয়েটিভ সিস্টেম।',
    outcome_tag_en: 'Most Popular for D2C Brands',
    outcome_tag_bn: 'D2C ব্র্যান্ডদের সর্বাধিক পছন্দের',
    deliverables_en: [
      '15 High-Converting Ad & Feed Creatives / mo',
      'High-Trust Storefront / PDP Conversion Graphics',
      'Persuasive Bengali Sales Copy for Every Creative',
      'AOV-Maximizing Combo & Bundle Offer Visuals',
      'Unlimited Revisions & Direct WhatsApp Priority Support',
    ],
    deliverables_bn: [
      'মাসে ১৫টি হাই-কনভার্টিং ফিড ও অ্যাড ক্রিয়েটিভ',
      'হাই-ট্রাস্ট স্টোরফ্রন্ট / PDP কনভার্শন গ্রাফিক্স',
      'প্রতিটি ক্রিয়েটিভের জন্য মনস্তাত্ত্বিক বাংলা সেলস কপি',
      'গড় অর্ডার ভ্যালু (AOV) বৃদ্ধিকারী কম্বো অফার আর্ট',
      'আনলিমিটেড রিভিশন ও প্রায়োরিটি হোয়াটসঅ্যাপ চ্যানেল',
    ],
    cta_en: 'Start Growth Engine',
    cta_bn: 'গ্রোথ পার্টনারশিপ শুরু করুন',
    whatsapp_url: "https://wa.me/8801346288210?text=Hi%20POLISHED%2C%20I%20am%20interested%20in%20the%20D2C%20Brand%20Growth%20Engine%20(%E0%A7%B332299/mo).",
    featured: true,
  },
  {
    id: 'agency-pack',
    title_en: 'White-Label Agency Partner',
    title_bn: 'হোয়াইট-লেবেল এজেন্সি পার্টনার',
    target_en: 'Performance Marketing Agencies',
    target_bn: 'ডিজাইনারের প্যারা ছাড়া এজেন্সি স্কেলিং',
    price_en: '৳48,500 / month',
    price_bn: '৳৪৮,৫০০ / মাস',
    desc_en: 'The invisible creative engine for marketing agencies. Scale client campaigns smoothly without hiring or managing in-house designers.',
    desc_bn: 'ইন-হাউস ডিজাইনার হায়ার ও ম্যানেজ করার সব প্যারা বাদ দিয়ে ক্লায়েন্টের বিজ্ঞাপনের ফলাফল বহুগুণ স্কেল করার জন্য আপনার ইনভিজিবল ব্যাকএন্ড।',
    outcome_tag_en: 'Scale Without Team Headaches',
    outcome_tag_bn: 'টিম হ্যাসেল ছাড়া ক্লায়েন্ট স্কেলিং',
    deliverables_en: [
      'Up to 30 White-Label Client Creatives / mo',
      'Strict 48-Hour Rapid Sprint Delivery SLA',
      'White-Label Figma / Drive (Zero POLISHED Branding)',
      'High ROAS Angles Designed to Retain Clients',
      'Direct WhatsApp / Slack Channel with Creative Lead',
    ],
    deliverables_bn: [
      'মাসে সর্বোচ্চ ৩০টি হোয়াইট-লেবেল ক্লায়েন্ট ক্রিয়েটিভ',
      'কঠোর ৪৮ ঘণ্টার র্যাপিড ডেলিভারি SLA',
      'হোয়াইট-লেবেল ফিগমা/ড্রাইভ (আমাদের কোনো নাম থাকবে না)',
      'ক্লায়েন্ট রিটেনশন ও আরওএএস সর্বোচ্চ করার আর্কিটেকচার',
      'ক্রিয়েটিভ লিডের সাথে ডিরেক্ট স্ল্যাক/হোয়াটসঅ্যাপ চ্যানেল',
    ],
    cta_en: 'Join Agency Program',
    cta_bn: 'এজেন্সি পার্টনারশিপ শুরু করুন',
    whatsapp_url: "https://wa.me/8801346288210?text=Hi%20POLISHED%2C%20I%20am%20interested%20in%20the%20White-Label%20Agency%20Partner%20Plan%20(%E0%A7%B348500/mo).",
    featured: false,
  },
];

export const DEFAULT_PRICING: PricingContent = {
  labelEn: 'Direct Investment & Profit',
  labelBn: 'স্বচ্ছ বিনিয়োগ ও আসল লাভ',
  titleEn: 'Stop Guessing.',
  titleEmEn: 'Pay for ads that actually convert.',
  titleBn: 'বিজ্ঞাপনে আর লস নয়।',
  titleEmBn: 'আসল সেলস আনার সিস্টেমে আসুন।',
  customHeadingEn: 'Need a Custom Scale Solution?',
  customHeadingBn: 'কাস্টম স্কেলিং সাপোর্ট প্রয়োজন?',
  customDescEn: "Managing higher ad spend or a multi-brand portfolio? Let's build a dedicated performance creative setup for your exact P&L targets.",
  customDescBn: 'বড় বাজেটের বিজ্ঞাপন বা একাধিক ব্র্যান্ড চালাচ্ছেন? আপনার নির্দিষ্ট বিজনেস মডেল অনুযায়ী কাস্টম সমাধান তৈরি করতে কথা বলুন।',
  customCtaEn: 'Talk to Creative Director',
  customCtaBn: 'সরাসরি কথা বলুন',
  tiers: DEFAULT_PRICING_TIERS,
};

export function makePricingTierId() {
  return `tier-${Math.random().toString(36).slice(2, 9)}`;
}
