import type { PricingContent, PricingTier } from '@/types/database';

export const DEFAULT_PRICING_TIERS: PricingTier[] = [
  // ── TRACK 1: VOLUME ENGINE (LOW-TICKET) ──
  {
    id: 'pkg-01',
    track: 'volume',
    title_en: 'Skincare Starter Sprint (PKG-01)',
    title_bn: 'স্কিনকেয়ার ট্রায়াল প্যাক (PKG-01)',
    target_en: 'Zero-Risk Test Offer for E-Commerce',
    target_bn: 'জিরো-ঝুঁকি টেস্ট অফার (প্রথম অনবোর্ডিং)',
    price_en: '৳999',
    price_bn: '৳৯৯৯',
    desc_en: 'Zero-risk starter sprint for small & medium e-commerce pages. 5 high-quality product banners with professional Bengali sales copy.',
    desc_bn: 'যেকোনো ছোট ও মাঝারি এফ-কমার্স পেজের প্রথম অনবোর্ডিং। ৫টি হাই-কোয়ালিটি প্রোডাক্ট ব্যানার ও প্রফেশনাল বাংলা সেলস কপি।',
    outcome_tag_en: '৳200 / Banner • Zero Risk',
    outcome_tag_bn: '৳২০০ / ব্যানার • জিরো রিস্ক',
    deliverables_en: [
      '5 High-Quality Product Banners (Offer, Ingredients, Benefits, Review, Combo)',
      'Professional High-Converting Bengali Sales Copy',
      'Strict 72-Hour Rapid Delivery Guarantee',
      '100% Bespoke Craft (Zero Recycled Templates)',
      'bKash, Nagad & Local Bank Payment Support',
      'Free Minor Revisions Guarantee',
    ],
    deliverables_bn: [
      '৫টি হাই-কোয়ালিটি স্কিনকেয়ার ব্যানার (অফার, উপাদান, বেনিফিট, রিভিউ, কম্বো)',
      'প্রফেশনাল ও কনভার্শন-অপটিমাইজড বাংলা সেলস কপি',
      '৭২ ঘণ্টার নির্ভরযোগ্য ডেলিভারি',
      '১০০% কাস্টম ক্রাফট (কোনো তৈরি টেমপ্লেট নয়)',
      'বিকাশ, নগদ ও ব্যাংক পেমেন্ট সাপোর্ট',
      'বিনামূল্যে রিভিশন সাপোর্ট',
    ],
    cta_en: 'Start ৳999 Trial Sprint',
    cta_bn: '৳৯৯৯ ট্রায়াল শুরু করুন',
    whatsapp_url: 'https://wa.me/8801346288210?text=Hi%20POLISHED%2C%20I%20want%20to%20start%20the%20%E0%A7%B3999%20Starter%20Trial%20Sprint%20(PKG-01).',
    featured: false,
  },
  {
    id: 'pkg-02',
    track: 'volume',
    title_en: 'E-Commerce Growth Retainer (PKG-02)',
    title_bn: 'এফ-কমার্স গ্রোথ প্যাক (PKG-02)',
    target_en: 'Regular Monthly Partnership (3 posts/week)',
    target_bn: 'মাসিক রেগুলার পার্টনারশিপ (সপ্তাহে ৩টি পোস্ট)',
    price_en: '৳2,299 / month',
    price_bn: '৳২,২৯৯ / মাস',
    desc_en: 'The core monthly creative engine for active pages. 12 high-converting banners plus free Facebook cover design with zero designer hiring headaches.',
    desc_bn: 'ছোট ও মাঝারি সক্রিয় পেজ যাদের নিয়মিত পোস্ট দরকার। ১২টি প্রিমিয়াম ব্যানার ও ফ্রি কভার ডিজাইন সহ পূর্ণাঙ্গ মাসিক সাপোর্ট।',
    outcome_tag_en: '৳191 / Banner • Most Popular',
    outcome_tag_bn: '৳১৯১ / ব্যানার • সর্বাধিক জনপ্রিয়',
    deliverables_en: [
      '12 High-Quality Banners (Strict 3 Banners Delivered Weekly)',
      '1 Free Professional Facebook Page Cover Design',
      'Persuasive Bengali & English Sales Copy for Each Post',
      'Unlimited Minor Revisions & Fast Turnaround',
      'Photoshop-Grade Luxury Visual Craft',
      'Direct Priority WhatsApp Communication',
    ],
    deliverables_bn: [
      '১২টি হাই-কোয়ালিটি ব্যানার (প্রতি সপ্তাহে নিয়মিত ৩টি ডেলিভারি)',
      '১টি ফ্রি প্রফেশনাল ফেসবুক পেজ কভার ডিজাইন',
      'প্রতিটি পোস্টের জন্য ধারালো বাংলা ও ইংরেজি সেলস কপি',
      'আনলিমিটেড মাইনর রিভিশন ও দ্রুত সাপোর্ট',
      'ফটোশপ-লেভেল প্রিমিয়াম ভিজ্যুয়াল কোয়ালিটি',
      'ডিরেক্ট হোয়াটসঅ্যাপ প্রায়োরিটি চ্যানেল',
    ],
    cta_en: 'Book Growth Retainer',
    cta_bn: 'গ্রোথ প্যাক বুক করুন',
    whatsapp_url: 'https://wa.me/8801346288210?text=Hi%20POLISHED%2C%20I%20want%20to%20book%20the%20E-Commerce%20Growth%20Retainer%20(%E0%A7%B32299/mo).',
    featured: true,
  },
  {
    id: 'pkg-03',
    track: 'volume',
    title_en: 'High-Volume Scale Retainer (PKG-03)',
    title_bn: 'এফ-কমার্স হাই-ভলিউম প্যাক (PKG-03)',
    target_en: 'Active Scale Pages (5 posts/week or campaigns)',
    target_bn: 'সক্রিয় পেজ (সপ্তাহে ৫টি পোস্ট বা ক্যাম্পেইন চলা পেজ)',
    price_en: '৳3,999 / month',
    price_bn: '৳৩,৯৯৯ / মাস',
    desc_en: 'High-frequency social volume to maximize reach and campaign momentum. 20 banners plus a 5-slide educational combo carousel.',
    desc_bn: 'একটু বেশি পোস্ট দেওয়া সক্রিয় পেজ ও ক্যাম্পেইন। ২০টি ব্যানার, ৫-স্লাইড এডুকেশনাল ক্যারোসেল ও ২টি অফার কভার ব্যানার।',
    outcome_tag_en: '৳160 / Banner • Best Value',
    outcome_tag_bn: '৳১৬০ / ব্যানার • সেরা ভ্যালু',
    deliverables_en: [
      '20 Social Media Banners (5 Strategic Posts / Week)',
      '1 Step-by-Step Educational Combo Carousel (5 Slides)',
      '2 High-Impact Offer Campaign Cover Banners',
      'AOV-Maximizing Combo & Bundle Visual Strategy',
      'Dedicated Creative Queue & Minor Revisions',
      'Official Monthly Invoicing & Agreement',
    ],
    deliverables_bn: [
      '২০টি সোশ্যাল মিডিয়া ব্যানার (সপ্তাহে ৫টি নিয়মিত পোস্ট)',
      '১টি স্টেপ-বাই-স্টেপ এডুকেশনাল কম্বো ক্যারোসেল (৫ স্লাইড)',
      '২টি হাই-ইমপ্যাক্ট ক্যাম্পেইন অফার কভার ব্যানার',
      'গড় অর্ডার ভ্যালু (AOV) বৃদ্ধির কম্বো ভিজ্যুয়াল',
      'ডেডিকেটেড ক্রিয়েটিভ সাপোর্ট ও রিভিশন',
      'অফিসিয়াল ইনভয়েস ও চুক্তিপত্র',
    ],
    cta_en: 'Start Scale Retainer',
    cta_bn: 'হাই-ভলিউম প্যাক শুরু করুন',
    whatsapp_url: 'https://wa.me/8801346288210?text=Hi%20POLISHED%2C%20I%20want%20to%20start%20the%20High-Volume%20Scale%20Retainer%20(%E0%A7%B33999/mo).',
    featured: false,
  },

  // ── TRACK 2: PERFORMANCE AD SPRINT ──
  {
    id: 'pkg-04',
    track: 'performance',
    title_en: 'Meta Ad Rescue Sprint (PKG-04)',
    title_bn: 'মেটা অ্যাড রেসকিউ স্প্রিন্ট (PKG-04)',
    target_en: 'Brands spending $500+ (৳60k+) on Meta with rising CPR',
    target_bn: 'মাসে ৳৬০,০০০+ স্পেন্ড করা ব্র্যান্ড যাদের CPR বেড়ে গেছে',
    price_en: '৳4,999',
    price_bn: '৳৪,৯৯৯',
    desc_en: 'For brands spending ৳60,000+ monthly where ad fatigue has spiked CPR. 4 psychological angle variations plus educational swipe carousel.',
    desc_bn: 'যেসব ব্র্যান্ড প্রতি মাসে ৳৬০,০০০+ বিজ্ঞাপনে খরচ করছে কিন্তু CPR বেড়ে গেছে। অ্যাড ফ্যাটিগ রোধে ৪টি সাইকোলজিক্যাল অ্যাঙ্গেল ও সোয়াইপ ক্যারোসেল।',
    outcome_tag_en: '৳1,000 / Ad Set • CPR Drop Focus',
    outcome_tag_bn: '৳১,০০০ / অ্যাড সেট • CPR কমানোর জন্য',
    deliverables_en: [
      '4 Psychological Angle-Based Meta Ad Variations (Hook Testing)',
      '1 Step-by-Step Educational Swipe Carousel (Feed & Story)',
      'Conversion-Optimized Culturally Persuasive Bengali Copywriting',
      '100% Meta Ad Policy Compliant Guarantee (Zero Restrictions)',
      'Strict 48-Hour Rapid Delivery Guarantee',
      'Visual Teardown & Creative Angle Strategic Brief',
    ],
    deliverables_bn: [
      '৪টি সাইকোলজিক্যাল অ্যাঙ্গেল বেসড মেটা অ্যাড ভ্যারিয়েশন (হুক টেস্টিং)',
      '১টি এডুকেশনাল সোয়াইপ ক্যারোসেল (ফিড ও স্টোরি সাইজ)',
      'কনভার্সন অপটিমাইজড মার্জিত বাংলা সেলস কপিরাইটিং',
      '১০০% মেটা অ্যাড পলিসি সুরক্ষিত গ্যারান্টি (জিরো রেস্ট্রিকশন)',
      '৪৮ ঘণ্টার নিশ্চিত দ্রুত স্প্রিন্ট ডেলিভারি',
      'ভিজ্যুয়াল টিয়ারডাউন ও ক্রিয়েটিভ অ্যাঙ্গেল ব্রিফ',
    ],
    cta_en: 'Claim ৳4,999 Rescue Sprint',
    cta_bn: '৳৪,৯৯৯ রেসকিউ স্প্রিন্ট নিন',
    whatsapp_url: 'https://wa.me/8801346288210?text=Hi%20POLISHED%2C%20I%20want%20to%20book%20the%20Meta%20Ad%20Rescue%20Sprint%20(PKG-04).',
    featured: false,
  },
  {
    id: 'pkg-05',
    track: 'performance',
    title_en: 'Growth Creative Partner (PKG-05)',
    title_bn: 'গ্রোথ ক্রিয়েটিভ পার্টনার (PKG-05)',
    target_en: 'Established D2C & K-Beauty Brands (৳1.5L - ৳3L+ Ad Spend)',
    target_bn: 'প্রতিষ্ঠিত ডিটুসি ও কে-বিউটি ব্র্যান্ড (মাসে ৳১.৫L - ৳৩L+ অ্যাড স্পেন্ড)',
    price_en: '৳14,999 / month',
    price_bn: '৳১৪,৯৯৯ / মাস',
    desc_en: 'Dedicated creative backend for brands spending ৳1.5L to ৳3L+ monthly on Meta. 16 performance creatives refreshed weekly to eliminate ad fatigue.',
    desc_bn: 'মাসে ৳১.৫ লাখ থেকে ৳৩ লাখ+ মেটা স্পেন্ড করা ব্র্যান্ডের সার্বক্ষণিক পার্টনার। সাপ্তাহিক ৪টি করে ১৬টি ক্রিয়েটিভ যা অ্যাড ফ্যাটিগ দূর করে স্কেলিং ধরে রাখে।',
    outcome_tag_en: '৳750 / Ad Asset • Scaling Partner',
    outcome_tag_bn: '৳৭৫০ / অ্যাড অ্যাসেট • স্কেলিং পার্টনার',
    deliverables_en: [
      '16 Performance Ad Creatives (Weekly 4 Fresh Assets to Kill Ad Fatigue)',
      '2 High-Conversion Educational & Social Proof Carousels',
      'Continuous Hook Testing, Iteration & Policy Compliance',
      'Bespoke Angle Architecture & Persuasive Bengali/EN Copy',
      'Direct WhatsApp Channel with Creative Director',
      'Monthly Creative Retrospective & Scaling Report',
    ],
    deliverables_bn: [
      '১৬টি পারফরম্যান্স অ্যাড ক্রিয়েটিভ (সাপ্তাহিক ৪টি রিফ্রেশ যা ফ্যাটিগ রোধ করে)',
      '২টি হাই-কনভার্সন এডুকেশনাল ও সোশ্যাল প্রুফ ক্যারোসেল',
      'কন্টিনিউয়াস হুক অপটিমাইজেশন, ইটারেশন ও পলিসি কমপ্লায়েন্স',
      'কাস্টম অ্যাঙ্গেল আর্কিটেকচার ও বাংলা/ইংরেজি সেলস কপি',
      'ক্রিয়েটিভ ডিরেক্টরের সাথে সরাসরি হোয়াটসঅ্যাপ চ্যানেল',
      'মাসিক ক্রিয়েটিভ অ্যানালাইসিস ও স্কেলিং রিপোর্ট',
    ],
    cta_en: 'Start Creative Partnership',
    cta_bn: 'পার্টনারশিপ রিটেইনার শুরু করুন',
    whatsapp_url: 'https://wa.me/8801346288210?text=Hi%20POLISHED%2C%20I%20want%20to%20partner%20on%20the%20Growth%20Creative%20Partner%20Plan%20(%E0%A7%B314999/mo).',
    featured: true,
  },
];

export const DEFAULT_PRICING: PricingContent = {
  labelEn: 'Direct Investment & Profit',
  labelBn: 'স্বচ্ছ বিনিয়োগ ও আসল লাভ',
  titleEn: 'Stop Guessing.',
  titleEmEn: 'Pay for ads that actually convert.',
  titleBn: 'বিজ্ঞাপনে আর লস নয়।',
  titleEmBn: 'আসল সেলস আনার সিস্টেমে আসুন।',
  customHeadingEn: 'Need a Custom Scale Solution?',
  customHeadingBn: 'কাস্টম স্কেলিং সাপোর্ট প্রয়োজন?',
  customDescEn: "Managing higher ad spend or a multi-brand portfolio? Let's build a dedicated performance creative setup for your exact P&L targets.",
  customDescBn: 'বড় বাজেটের বিজ্ঞাপন বা একাধিক ব্র্যান্ড চালাচ্ছেন? আপনার নির্দিষ্ট বিজনেস মডেল অনুযায়ী কাস্টম সমাধান তৈরি করতে কথা বলুন।',
  customCtaEn: 'Talk to Creative Director',
  customCtaBn: 'সরাসরি কথা বলুন',
  tiers: DEFAULT_PRICING_TIERS,
};

export function makePricingTierId() {
  return `tier-${Math.random().toString(36).slice(2, 9)}`;
}
